# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20170311_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='ref',
            field=models.TextField(blank=True),
        ),
    ]
