# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_auto_20170315_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='x',
        ),
        migrations.RemoveField(
            model_name='page',
            name='y',
        ),
    ]
