# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_auto_20170315_0900'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
